name: Build kpatch

on:
  push:
  pull_request:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/kpatch
    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Install build tools
        run: |
          sudo apt update
          sudo apt install -y build-essential

      - name: Build kpatch binaries
        run: make

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ${{ github.workspace }}/src
          commit-message: Deploy
          single-commit: true
